export const restaurants = [
    {
        name: "McDonald's",
        type: "Fast-Food",
        desc: "img/card-McDonald's.jpg",
        img: "https://images.unsplash.com/photo-1619881589316-56c7f9e6b587?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWNkb25hbGQnc3xlbnwwfDB8MHx8fDA%3D",
        burger: true,
        range: "(190m)",
        avis: "Avis : 504",
        note: "Note : 4,4/5",
        prix: "Prix : 16,90€ ",
    },
    {
        name: "Burger King",
        type: "Fast-Food",
        desc: "Hamburger, wrap, desserts... Sur place ou à emporter.",
        img: "img/card-Burger-King.jpg",
        burger: true,
        range: "(231m)",
        avis: "Avis : 632",
        note: "Note : 4,9/5",
        prix: "Prix : 14,90€ ",
    },
    {
        name: "KFC",
        type: "Fast-Food",
        desc: "Hamburger, wings, tenders... Sur place ou à emporter.",
        img: "img/card-KFC.jpg",
        burger: true,
        range: "(698m)",
        avis: "Avis : 504",
        note: "Note : 4,2/5",
        prix: "Prix : 12,70€ ",
    },

    {
        name: "Pepe Chicken",
        type: "Fast-Food",
        desc: "Hamburger, wings, tenders... Sur place ou à emporter.",
        img: "img/card-Pepe-Chicken.jpg",
        burger: true,
        range: "(2,7km)",
        avis: "Avis : 554",
        note: "Note : 4,9/5",
        prix: "Prix : 14,70€ ",

    },
    {
        name: "231 East Street",
        type: "Artisanal",
        desc: "Burgers gourmets, frites maison...Sur place ou à emporter.",
        img: "img/card-231-Street-Burger.jpg",
        burger: true,
        range: "(1,2km)",
        avis: "Avis : 202",
        note: "Note : 4,8/5",
        prix: "Prix : 13,50€ ",
    },
    {
        name: "Street Burger",
        type: "Artisanal",
        desc: "Hamburger, frites, desserts... Sur place ou à emporter.",
        img: "img/card-Street-Burger.jpg",
        burger: true,
        range: "(1,1km)",
        avis: "Avis : 415",
        note: "Note : 4,3/5",
        prix: "Prix : 16,70€ ",
    },
    {
        name: "Smash Burger",
        type: "Artisanal",
        desc: "Hamburger smash, tenders... Sur place ou à emporter.",
        img: "img/card-Smash-Burger.jpg",
        burger: true,
        range: "(990m)",
        avis: "Avis : 301",
        note: "Note : 4,6/5",
        prix: "Prix : 15,90€ ",
    },

    {
        name: "Burger Fries",
        type: "Artisanal",
        desc: "Hamburger grillés, tenders... Sur place ou à emporter.",
        img: "img/card-Bruger-Fries.jpg",
        burger: true,
        range: "(984m)",
        avis: "Avis : 376",
        note: "Note : 4,7/5",
        prix: "Prix : 17,90€ ",
    },
    {
        name: "Boulangerie Ange",
        type: "Boulangerie",
        desc: "Burgers fait maison, frites...Sur place ou à emporter.",
        img: "img/card-Boulangerie-Ange.jpg",
        burger: true,
        range: "(3,8km)",
        avis: "Avis : 105",
        note: "Note : 4,9/5",
        prix: "Prix : 10,90€ ",
    },
    {
        name: "Boulangerie Paul",
        type: "Boulangerie",
        desc: "Burgers fait maison, boisson fraiche...Sur place ou à emporter.",
        img: "img/card-Boulabgerie-Paul.jpg",
        burger: true,
        range: "(2,2km)",
        avis: "Avis : 277",
        note: "Note : 4,6/5",
        prix: "Prix : 11,90€ ",
    },
    {
        name: "Boulangerie Belet",
        type: "Boulangerie",
        desc: "Burgers délicieux, frites bio...Sur place ou à emporter.",
        img: "img/card-Boulangerie-Belet.jpg",
        burger: true,
        range: "(1,3km)",
        avis: "Avis : 256",
        note: "Note : 4,3/5",
        prix: "Prix : 9,90€ ",
    },

    {
        name: "Boulangerie 3L",
        type: "Boulangerie",
        desc: "Burgers tendre, frites bio...Sur place ou à emporter.",
        img: "img/card-Boulangerie-3L.jpg",
        burger: true,
        range: "(1,5km)",
        avis: "Avis : 226",
        note: "Note : 4,1/5",
        prix: "Prix : 10,90€ ",
    },
]