export const data = [
    {
        nom: "My Beers",
        distance: "220m",
        type: "Bar",
        description: "Bieres pression ou bouteille, sur place ou à emporter",
        adresse: "63, quai Virgine Hériot 33300 Bordeaux",
        Tel: "0556379543",
    },
    {
        nom: "Delirium",
        distance: "650m",
        type: "Brunch",
        description: "Bières, sport, salle de jeux",
        adresse: "30, quai Virgine Hériot 33300 Bordeaux",
        Tel: "",
    },
    {
        nom: "Mc Donald’s",
        distance: "190m",
        type: "Burger",
        description: "Hamburger, wrap, salades, desserts... Sur place ou à emporter",
        adresse: "Place Latule, 33300 BORDEAUX",
        Tel: "05 57 19 11 87",
    },
    {
        nom: "231 East Street",
        distance: "600m",
        type: "Burger",
        description: "le vrai burger New - Yorkais, ses frites, ses cookies",
        adresse: "17, quai Virgine Hériot 33300 Bordeaux",
        Tel: "05 57 02 10 1663",
    },
    {
        nom: "Italian Trattoria",
        distance: "600m",
        type: "Pizza",
        description: "Pizzas, pâtes",
        adresse: "40, quai Virgine Hériot 33300 Bordeaux",
        Tel: "05 57 02 09 76",
    },
    {
        nom: "Flam’s",
        distance: "650m",
        type: "Pizza",
        description: "Flammekueche, menu vegetarien, repas de groupe",
        adresse: "17 Quai Virginie Hériot, 33000 Bordeaux",
        Tel: "05 57 02 10 15",
    },
    {
        nom: "Bass’bill",
        distance: "450m",
        type: "Brunch",
        description: "",
        adresse: "61 Quai Virginie Hériot, 33000 Bordeaux",
        Tel: "05 57 82 70 33",
    },
];